import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ul className="inline-flex pb-6 text-xl ">
        <li className="pr-6 pl-6"><Link href={'/'}>Home</Link></li>
        <li className="pr-6"><Link href={'/spells'}>Spells</Link></li>
        <li className="pr-6"><Link href={'/monsters'}>Monsters</Link></li>
        </ul>
        <>
        {children}
        </>
      </body>
    </html>
  )
}
